ResumeMVC/Controllers/ResumeController.cs
using AutoMapper;
using ResumeMVC.EDMXModel;
using ResumeMVC.Repository;
using ResumeMVC.ViewModels;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using AutoMapper.QueryableExtensions;
using System.Data.Entity;
using System.Net;
using System.Threading.Tasks;
using System.IO;
using ResumeMVC.Models;
using Rotativa;
using Microsoft.AspNet.Identity;
using System;
using Syncfusion.Pdf;
using Syncfusion.Pdf.Graphics;
using System.Drawing;

namespace ResumeMVC.Controllers
{
    public class ResumeController : Controller
    {
        private readonly DBCVEntities _dbContext = new DBCVEntities();
        private readonly DBCVEntities1 _dbContext1 = new DBCVEntities1();

        private readonly IResumeRepository _resumeRepository;
        public ResumeController(IResumeRepository resumeRepository)
        {
            _resumeRepository = resumeRepository;
        }

        // Test Azure Devops Test Commit to

        // GET: Resume
        public ActionResult Index()
        {
            return View();
        }

        [HttpGet]
        [ActionName("Employees")]
        public async Task<ActionResult> Employees(LoginViewModel model)
        {

            if (Session["UserName"] != null)
            {
                return View(await _dbContext.People.ToListAsync());
            }
            else
            {
                return RedirectToAction("Login");
            }

            //Bharath Added
        }
        public ActionResult Login(string returnUrl)
        {
            ViewBag.isAuth = false;
            ViewBag.ReturnUrl = returnUrl;
            return View();
        }



        [ActionName("LogOff")]
        public ActionResult LogOff()
        {
            Session["UserID"] = null;
            Session["UserName"] = null;
            return RedirectToAction("Login");
        }

        [ActionName("Dashboard")]
        public ActionResult Dashboard()
        {
            try
            {
                return View();
            }
            catch (Exception ex)
            {
                return RedirectToAction("Login");
            }

        }
        //The login form is posted to this method.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Login(LoginViewModel model)
        {
            //Checking the state of model passed as parameter.
            if (ModelState.IsValid)
            {

                //Validating the user, whether the user is valid or not.
                var isValidUser = IsValidUser(model);

                if (isValidUser != null)
                {
                    if (isValidUser.Email == "admin@cv.com")
                    {
                        Session["UserName"] = model.Email.ToString();
                        return RedirectToAction("Dashboard");
                    }
                    else
                    {
                        try
                        {
                            Person person = _dbContext.People.Where(query => query.Email.Equals(model.Email)).SingleOrDefault();
                            if (person != null)
                            {
                                Session["UserName"] = model.Email.ToString();
                                return RedirectToAction("UserDashBoard", new { id = person.IDPers });
                            }
                            else
                            {
                                Session["UserName"] = model.Email.ToString();
                                return RedirectToAction("UserDashBoard");
                            }

                        }
                        catch (Exception ex)
                        {

                            ModelState.AddModelError("Failure", "Wrong Username and password combination !");
                            return View();
                        }
                    }
                }
                else
                {
                    ModelState.AddModelError("Failure", "Wrong Username and password combination !");
                    return View();
                }
            }
            else
            {
                //If model state is not valid, the model with error message is returned to the View.
                return View(model);
            }
        }

        [HttpGet]
        [ActionName("UserDashBoard")]
        // GET: Employees/EmployeesDetails/5
        public async Task<ActionResult> UserDashBoard(int? id)
        {

            if (Session["UserName"] != null)
            {
                try
                {
                    Person Person = await _dbContext.People.FindAsync(id);
                    return View(Person);
                }
                catch (Exception ex)
                {
                    return null;
                }
            }
            else
            {
                return RedirectToAction("Login");
            }
        }


        public ActionResult Welcome()
        {
            return View();
        }

        public Login IsValidUser(LoginViewModel model)
        {
            using (_dbContext1)
            {
                try
                {
                    Login user = _dbContext1.Logins.Where(query => query.Email.Equals(model.Email) && query.password.Equals(model.Password)).SingleOrDefault();
                    if (user == null)
                    {
                        if (model.Email == "admin@cv.com" && model.Password == "admin@cv.com")
                        {
                            Login user1 = new Login();
                            user1.Email = model.Email;
                            return user1;
                        }
                        else
                        {
                            ModelState.AddModelError("", "Invalid login attempt.");
                            return null;
                        }

                    }
                    else
                        return user;
                }
                catch
                {
                    ModelState.AddModelError("", "Invalid login attempt.");
                    return null;
                }

            }
        }

        // GET: /Account/Register
        [AllowAnonymous]
        public ActionResult Register()
        {
            return View();
        }



        [HttpPost]
        public ActionResult SaveRegisterDetails(Login registerDetails)
        {
            if (ModelState.IsValid)
            {
                //create database context using Entity framework 
                using (_dbContext1)
                {
                    try
                    {
                        //If the model state is valid i.e. the form values passed the validation then we are storing the User's details in DB.
                        Login reglog = new Login();

                        //Save all details in RegitserUser object
                        reglog.Email = registerDetails.Email;
                        reglog.password = registerDetails.password;
                        try
                        {
                            Login user = _dbContext1.Logins.Where(query => query.Email.Equals(reglog.Email) && query.password.Equals(reglog.password)).SingleOrDefault();
                            if (user == null)
                            {
                                _dbContext1.Logins.Add(reglog);
                                _dbContext1.SaveChanges();
                                ViewBag.Message = "User Details Saved";
                                return View("Login");
                            }
                            else
                            {
                                ModelState.AddModelError("", "Email Allreday Exist");
                                return View("Login");
                            }
                        }
                        catch
                        {
                            ViewBag.Message = "Email Already Exit ";
                            return View("Login");
                        }
                    }
                    catch
                    {
                        ViewBag.Message = "User Details Saved";
                        return View("Login");
                    }
                }
            }
            else
            {

                //If the validation fails, we are returning the model object with errors to the view, which will display the error messages.
                return View("Register", registerDetails);
            }
        }


        [HttpGet]
        [ActionName("DownloadCv")]
        public ActionResult DownloadCv(int id)
        {
            return new ActionAsPdf("DownloadCvPdf", new { id = id })
            {
                FileName = Server.MapPath("~/Files/YourCv.pdf")
            };
        }

        public ActionResult GeneratePDF()
        {
            //Create a new PdfDocument
            PdfDocument document = new PdfDocument();

            //Add a page to the document
            PdfPage page = document.Pages.Add();

            //Create Pdf graphics for the page
            PdfGraphics graphics = page.Graphics;

            //Create a solid brush
            PdfBrush brush = new PdfSolidBrush(Color.Black);

            //Set the font
            PdfFont font = new PdfStandardFont(PdfFontFamily.Helvetica, 20f);

            //Draw the text
            graphics.DrawString("Hello world!", font, brush, new PointF(20, 20));

            MemoryStream stream = new MemoryStream();
            document.Save(stream);

            Response.Clear();
            Response.ClearContent();
            Response.Write(Convert.ToBase64String(stream.ToArray()));
            Response.Flush();
            Response.End();
            return View();
        }

        [HttpGet]
        [ActionName("DownloadCvPdf")]
        // GET: Employees/EmployeesDetails/5

ResumeMVC/Views/Shared/_Footer.cshtml
<div class="container">
    <div class="row">
        <div class="col-12 col-sm-6">
            Copyright© 2018 &nbsp; 
        </div>
        <div class="col-12 col-sm-6 float-right text-right">
        </div>
    </div>
</div>

ResumeMVC/Views/Shared/_Header.cshtml
<form>
    <div class="header collapse d-lg-flex p-0" id="headerMenuCollapse">
        <div class="container">
            <div class="row align-items-center">
                Cv Management
                <div class="col-lg order-lg-first">
                    <ul class="nav nav-tabs border-0 flex-column flex-lg-row">
                        <li class="nav-scape">&nbsp;</li>

                        <li class="nav-item">
                            <a href="@Url.Action("Dashboard", "Resume")" class="nav-link"><i class="fe fe-home"></i> Dashboard</a>
                        </li>

                        @*<li class="nav-item">
                    <a href="@Url.Action("CreateConsultant", "admin")" class="nav-link"><i class="fe fe-user"></i> Create Consultant</a>
                </li>


                <li class="nav-item">
                    <a href="@Url.Action("ListConsultant", "admin")" class="nav-link"><i class="fe fe-user"></i> Consultant List</a>
                </li>



                <li class="nav-item">
                    <a href="@Url.Action("ListUser", "admin")" class="nav-link"><i class="fe fe-user"></i> User List</a>
                </li>*@

                        @*<li class="nav-item">
                    <a href="@Url.Action("CreateConsultant", "admin")" class="nav-link"><i class="fe fe-user"></i> Create Consultant</a>
                </li>


                <li class="nav-item">
                    <a href="@Url.Action("ListConsultant", "admin")" class="nav-link"><i class="fe fe-user"></i> Consultant List</a>
                </li>



                <li class="nav-item">
                    <a href="@Url.Action("ListUser", "admin")" class="nav-link"><i class="fe fe-user"></i> User List</a>
                </li>*@

                        <li class="nav-item">
                            <a href="@Url.Action("Employees", "Resume")" class="nav-link"><i class="fa fa-id-badge"></i> Employees</a>
                        </li>

                        <li class="nav-item">
                            <a href="@Url.Action("LogOff", "Resume")" class="nav-link"><i class="fe fe-log-out"></i> Logout</a>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</form>

ResumeMVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title CV Management</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
   
    <style type="text/css">

        .field-validation-error {
            background-color: #e85555;
            color: white;
            padding: 2px 9px;
            border-radius: 9px;
            font-size: 12px;
        }

        .navbar.navbar-inverse.navbar-fixed-top {
            background-color: #FFAA0F !important;
            border-color: #FFAA0F !important;
        }

        .registerLinktext {
            color: white !IMPORTANT;
        }

        span.navbar-brand {
            color: white !important;
        }

        a#loginLink {
            color: white !important;
        }
    </style>

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <span class="navbar-brand">
                    Cv Management
                </span> @*@Html.ActionLink("Cv Management", "Employees", "Resume", new { area = "" }, new { @class = "navbar-brand" })*@
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    @*<li>@Html.ActionLink("MyCv", "Employees", "Resume")</li>*@
                    @*<li>@Html.ActionLink("About", "About", "Home")</li>
                        <li>@Html.ActionLink("Contact", "Contact", "Home")</li>*@
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content" style="margin-top: 113px;">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - CV Management </p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")

    @RenderSection("scripts", required: false)

    <script src="https://raw.githack.com/eKoopmans/html2pdf/master/dist/html2pdf.bundle.js"></script>
   
    <script type="text/javascript">
        $(function () {
            /*  $('#datetimepicker1').datetimepicker();*/
            $('#datetimepicker2').datetimepicker();
            $('#printpdf').click(function () {
                var x = document.getElementById("EditUrl");          
                    x.style.display = "none";          
                var element = document.getElementById('printpdf_cv');
                html2pdf().from(element).set({              
                }).save()
            });
        });
    </script>

    @section scripts {

        <script type="text/javascript">

            $(document).ready(function () {
                $('#datetimepicker1').data();
            }
        </script>
    }
</body>
</html>

ResumeMVC/Views/Shared/_LayoutAdmin.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title CV Management</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <link href="~/Content/BackEnd/dashboard.css" rel="stylesheet" />
    <link href="~/BackEnd/Plugins/charts-c3/plugin.css" rel="stylesheet" />
    <link href="~/BackEnd/Plugins/maps-google/plugin.css" rel="stylesheet" />
    <link href="~/Content/BackEnd/style.css" rel="stylesheet" />
  
    <style type="text/css">
        .field-validation-error {
            background-color: #e85555;
            color: white;
            padding: 2px 9px;
            border-radius: 9px;
            font-size: 12px;
        }

        .navbar.navbar-inverse.navbar-fixed-top {
            background-color: #FFAA0F !important;
            border-color: #FFAA0F !important;
        }

        .registerLinktext {
            color: white !IMPORTANT;
        }

        span.navbar-brand {
            color: white !important;
        }

        a#loginLink {
            color: white !important;
        }
    </style>

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <span class="navbar-brand">
                    Cv Management
                </span> @*@Html.ActionLink("Cv Management", "Employees", "Resume", new { area = "" }, new { @class = "navbar-brand" })*@
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Dashboard", "Dashboard", "Resume", new { @Style = "color: white" })</li>
                    <li>@Html.ActionLink("Employees", "Employees", "Resume", new { @Style = "color: white" })</li>
                    @*<li>@Html.ActionLink("About", "About", "Home")</li>
                        <li>@Html.ActionLink("Contact", "Contact", "Home")</li>*@
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content" style="margin-top: 113px;">
        @RenderBody()
        <footer>
            <p>&copy; @DateTime.Now.Year - CV Management </p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")

    @RenderSection("scripts", required: false)


    <script type="text/javascript">
        $(function () {
            /*  $('#datetimepicker1').datetimepicker();*/
            $('#datetimepicker2').datetimepicker();
        });
    </script>
    <script src="https://raw.githack.com/eKoopmans/html2pdf/master/dist/html2pdf.bundle.js"></script>

    <script type="text/javascript">
        $(function () {
            $('#printpdf').click(function () {
                var element = document.getElementById('printpdf_cv');
                html2pdf().from(element).set({
                    margin: [30, 10, 5, 10],
                    pagebreak: { avoid: '' },
                    jsPDF: { orientation: '', unit: 'pt', format: 'latter', compressPDF: true }
                }).save()
            });
        });
    </script>
    @section scripts {

        <script type="text/javascript">

            $(document).ready(function () {
                $('#datetimepicker1').data();

            }
        </script>
    }


</body>
</html>

ResumeMVC/Views/Shared/_MyCertificationCV.cshtml
@model IQueryable<ResumeMVC.ViewModels.CertificationVM>



<div class="panel panel-default">

    <div style="margin-left:3%; margin-top: 2%;">
        <span class="IconTitle" style="background-color:#f0ad4e">
            <span class="glyphicon glyphicon-file" aria-hidden="true" style="margin-left:26px; margin-top: 23px; color:#FFF;"></span>
        </span>

        <h4 style="margin-left: 12%; margin-top: -6%;">Certifications</h4>
    </div>

    <div class="panel-body">

       @if (Model != null && Model.Any())
       {
           foreach (var certification in Model)
           {
            <div class="box" style="border:none;">
                <div class="details">
                    <div style="display: block; width: 85px; margin-left: 13px;">
                       @CertificationAuthority(certification.CertificationAuthority)
                    </div>
                    <div style="margin-left: 11%; margin-top: -9%;">
                        <p style="margin-left: 4%; font-weight:bold;">
                            @certification.CertificationName
                            <span class="yearStyle" style="position: relative; left: 54%; background-color: #f0ad4e;"> @string.Format("{0: dd/mm/yyyy}", certification.FromYear)</span><br>
                        </p>
                        <span style="margin-left: 27px;"> <i>@certification.LevelCertification</i></span>
                    </div>

                </div> <!--END DETAILS-->

            </div> <!--END BOX-->
           }
       }
        

        

    </div> <!-- END PANEL BODY -->
</div> <!-- END PANEL DEFAULT CERTIFICATIONS -->


@helper CertificationAuthority(string authortiy)
{
switch (authortiy.ToLower())
{
    case "microsoft":
        @Helper.GetImage("ms.png");
        break;

    case "scrum":
        @Helper.GetImage("scrum.png");
        break;

    case "cisco":
        @Helper.GetImage("cisco.jpg");
        break;
}
}

ResumeMVC/Views/Shared/_MyEducation.cshtml
@model ResumeMVC.ViewModels.EducationVM

<style type="text/css">
    .row {
        margin-bottom: 25px;
    }

    .IconTitle {
        border: 3px solid #e0e0e0;
        display: inline-block;
        width: 70px;
        height: 70px;
        border-radius: 100%;
        background-color: #5cb85c;
    }
</style>

<div class="container">

    <div class="Education FirstLevel" >

        <div style="margin-left:18%;">
            <span class="IconTitle">
                <span class="glyphicon glyphicon-education" aria-hidden="true" style="margin-left:26px; margin-top: 23px; color:#FFF;"></span>
            </span>

            <h4 style="margin-left: 8%; margin-top: -4%;">Education</h4>
        </div>


        <div class="panel panel-default" style="width: 65%; margin-left: 18%; margin-top: 3%;">

            <div class="panel-heading">
                <h3 class="panel-title">Education</h3>
            </div> <!-- END PANEL HEADING -->
            <form>
                <div class="panel-body">

                    <div class="row">

                        <div class="col-xs-6">
                            @Html.EditorFor(model => model.InstituteUniversity, new { htmlAttributes = new { @class = "form-control", @placeholder = "Institute/University" } })
                            @Html.ValidationMessageFor(model => model.InstituteUniversity, "", new { @class = "text-danger" })
                        </div>

                        <div class="col-xs-6">
                            @Html.EditorFor(model => model.TitleOfDiploma, new { htmlAttributes = new { @class = "form-control", @placeholder = "Title Of Diploma" } })
                            @Html.ValidationMessageFor(model => model.TitleOfDiploma, "", new { @class = "text-danger" })
                        </div>

                    </div>

                    <div class="row">

                        <div class="col-xs-12">
                            @Html.EditorFor(model => model.Degree, new { htmlAttributes = new { @class = "form-control", @placeholder = "Degree" } })
                            @Html.ValidationMessageFor(model => model.Degree, "", new { @class = "text-danger" })
                        </div>

                    </div>

                    <div class="row">

                        <div class="col-xs-6">
                            <div class="form-group">
                                <div class="input-group date" id="datetimepicker1">
                                    @Html.EditorFor(model => model.FromYear, new { htmlAttributes = new { @class = "form-control", @placeholder = "From Year" } })
                                    <span class="input-group-addon">
                                        <span class="glyphicon glyphicon-calendar"></span>
                                    </span>
                                </div>
                            </div>
                            @Html.ValidationMessageFor(model => model.FromYear, "", new { @class = "text-danger" })
                        </div>

                        <div class="col-xs-6">
                            <div class="form-group">
                                <div class="input-group date" id="datetimepicker2">
                                    @Html.EditorFor(model => model.ToYear, new { htmlAttributes = new { @class = "form-control", @placeholder = "To Year" } })
                                    <span class="input-group-addon">
                                        <span class="glyphicon glyphicon-calendar"></span>
                                    </span>
                                </div>
                            </div>
                            @Html.ValidationMessageFor(model => model.ToYear, "", new { @class = "text-danger" })
                        </div>

                    </div>

                    <div class="row">

                        <div class="col-xs-6">

                            @Html.DropDownListFor(model => model.Country, Model.ListOfCountry, new { @class = "form-control" })

                        </div>

                        <div class="col-xs-6">

                            @Html.DropDownListFor(model => model.City, new List<SelectListItem>(), new { @class = "form-control" })

                        </div>

                    </div>

                    @Html.HiddenFor(model => model.IDEdu, new { @class = "form-control" })


                    <button type="button" id="AddOrUpdateEducation" class="btn btn-success"> <span class="glyphicon glyphicon-education" aria-hidden="true"></span>  Add Eduction </button>
                    <a href="@Url.Action("WorkExperience", "Resume")" class="btn btn-success" style="position: relative; right: -50%;"> Next Step>> Work Experience </a>

                </div> <!-- END PNEL BODY-->
            </form>
        </div>

    </div>   <!-- END EDUCATION FIRST LEVEL-->

</div> <!-- END CONTAINER -->

ResumeMVC/Views/Shared/_MyEducationCV.cshtml
@model IQueryable<ResumeMVC.ViewModels.EducationVM>



<div class="panel panel-default">

    <div style="margin-left:3%; margin-top: 2%;">
        <span class="IconTitle" style="background-color:#5cb85c">
            <span class="glyphicon glyphicon-education" aria-hidden="true" style="margin-left:26px; margin-top: 23px; color:#FFF;"></span>
        </span>

        <h4 style="margin-left: 12%; margin-top: -6%;">Education</h4>
    </div>

    <div class="panel-body">
@if (Model != null && Model.Any())
{
    foreach (var education in Model)
    {
        <div class="box">
            <div class="details">

             
                    <p style="margin-left: 4%;">
                        <b> @string.Format("{0} : {1}", education.InstituteUniversity, education.TitleOfDiploma) </b>
                        <span class="yearStyle" style="position: relative; left: 53%; background-color: #5cb85c;"> @string.Format("{0: yyyy} - {1: yyyy}", education.FromYear, education.ToYear)</span><br>
                        <span>@education.Degree</span><br>
                        <span> <i> @string.Format("{0} | {1}", @education.City, @education.Country) </i></span>
                    </p>

            </div> <!--END DETAILS-->

        </div> <!--END BOX-->
    }
}

    </div> <!-- END PANEL BODY -->
</div> <!-- END PANEL DEFAULT EDUCATION -->

ResumeMVC/Views/Shared/_MyPersonnalInfo.cshtml
@model ResumeMVC.ViewModels.PersonVM


<div class="panel panel-default">

    <div class="panel-body">

        <div id="Profil">

            <img  src="@Url.Action("GetProfilImage", "Resume", new { id = Model.IDPers})" alt="" class="img-circle" style="width: 125px; height: 142px; border: 3px solid #c1c1c1;" />

            <h4 style="display: inline-block; margin-left: 20px;">@string.Format("{0}, {1}", Model.LastName, Model.FirstName)</h4>

        </div> <!-- END PROFIL -->
        <a class="btn btn-primary" href="@Url.Action("GetProfilImage","Resume",new { id = Model.IDPers})">Download Cv</a>
        <div id="container">

            <div class="row" style="margin-top: 22px;">

                <div class="col-xs-4">
                    <p>
                        <b> Date Of Birth : </b> <span>@string.Format("{0:MM/dd/yyyy}", Model.DateOfBirth)</span>
                    </p>
                </div>
            </div>

            <div class="row">

                <div class="col-xs-4">
                    <p>
                        <b>Nationality :</b> <span>@Model.Nationality</span>
                    </p>
                </div>
            </div>

            <div class="row">

                <div class="col-xs-8">
                    <p>
                        <b>Address : </b> <span>@Model.Address</span>
                    </p>
                </div>
            </div>

            <div class="row">

                <div class="col-xs-3">
                    <p>
                        <b>Tel :</b> <span>@Model.Tel</span>
                    </p>
                </div>

                <div class="col-xs-4">
                    <p>
                        <b>E-mail :</b> <span>@Model.Email</span>
                    </p>
                </div>

                <div class="col-xs-5">
                    <p>
                        <b>Educational Level :</b> <span>@Model.EducationalLevel</span>
                    </p>
                </div>
            </div>
        </div>

        @*<div class="socialMedia" style="margin-left: 30%;">
            <a href="@Model.FaceBookProfil" class="btn btn-primary"> <i class="fa fa-facebook-official" aria-hidden="true"></i> Facebook</a>

            <a href="@Model.LinkedInProdil" class="btn btn-success"><i class="fa fa-linkedin-square" aria-hidden="true"></i> LinkedIN</a>

            <a href="@Model.C_CornerProfil" class="btn btn-warning">C#Corner</a>

            <a href="@Model.TwitterProfil" class="btn btn-info"><i class="fa fa-twitter-square" aria-hidden="true"></i> Twitter</a>
        </div>*@


    </div> <!-- END PANEL BODY / Personnal Information-->

</div> <!-- END PANEL DEFAULT-->

<div class="panel panel-default">

    <div style="margin-left:3%; margin-top: 2%;">
        <span class="IconTitle" style="background-color:#a9a9a9">
            <span class="glyphicon glyphicon-user" aria-hidden="true" style="margin-left:26px; margin-top: 23px; color:#FFF;"></span>
        </span>

        <h4 style="margin-left: 12%; margin-top: -6%;">Summary</h4>
    </div>

    <div class="panel-body">

        <p class="description">
           @Model.Summary
        </p>



    </div> <!-- END PANEL BODY -->
</div> <!-- END PANEL DEFAULT -->

ResumeMVC/Views/Shared/_View.cshtml
@model ResumeMVC.ViewModels.PersonVM

<h3>Bharath </h3>